services:
  - type: web
    name: mobile-ai-assistant
    env: python
    branch: branch_TestDeploySV
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "gunicorn backend.main:app"
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
