services:
  - type: web
    name: mobile-ai-assistant
    env: python
    branch: branch_TestDeploySV
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && gunicorn main:app"
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
