services:
  - type: web
    name: flask-chatbot
    env: python
    plan: free
    rootDir: backend  # 👉 Chỉ định đúng thư mục chứa main.py và requirements.txt

    buildCommand: pip install -r requirements.txt  # 👉 Vì requirements.txt nằm ngoài thư mục backend
    startCommand: gunicorn main:app
    autoDeploy: true
