services:
  - type: web
    name: mobile-assistant-backend
    env: python

    rootDir: backend  # <- Đây là dòng quan trọng

    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
